<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $products = [
            // Printing Supplies (category_id: 1)
            [
                'product_name' => 'Bond Paper A4',
                'barcode' => 'BP-A4-500',
                'description' => '500 sheets per ream, 80gsm',
                'category_id' => 1,
                'unit' => 'ream',
                'price' => 250.00,
                'cost' => 180.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Photo Paper 4R',
                'barcode' => 'PP-4R-100',
                'description' => 'Glossy photo paper, 100 sheets per pack',
                'category_id' => 1,
                'unit' => 'pack',
                'price' => 350.00,
                'cost' => 250.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Sublimation Paper A4',
                'barcode' => 'SP-A4-100',
                'description' => 'For sublimation printing, 100 sheets',
                'category_id' => 1,
                'unit' => 'pack',
                'price' => 180.00,
                'cost' => 120.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Ink Cartridge Black',
                'barcode' => 'IC-BK-001',
                'description' => 'Compatible with most printers',
                'category_id' => 1,
                'unit' => 'piece',
                'price' => 450.00,
                'cost' => 320.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Ink Cartridge Color',
                'barcode' => 'IC-CL-001',
                'description' => 'Tri-color ink cartridge',
                'category_id' => 1,
                'unit' => 'piece',
                'price' => 550.00,
                'cost' => 400.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ID Materials (category_id: 2)
            [
                'product_name' => 'PVC ID Card Blank',
                'barcode' => 'ID-PVC-100',
                'description' => 'Blank white PVC cards, 100 pieces',
                'category_id' => 2,
                'unit' => 'pack',
                'price' => 380.00,
                'cost' => 280.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Lanyard Standard',
                'barcode' => 'LY-STD-001',
                'description' => 'Standard lanyard with clip',
                'category_id' => 2,
                'unit' => 'piece',
                'price' => 25.00,
                'cost' => 15.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Lanyard Premium',
                'barcode' => 'LY-PRM-001',
                'description' => 'Premium quality lanyard with safety clip',
                'category_id' => 2,
                'unit' => 'piece',
                'price' => 45.00,
                'cost' => 30.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'ID Card Holder',
                'barcode' => 'CH-STD-001',
                'description' => 'Transparent card holder',
                'category_id' => 2,
                'unit' => 'piece',
                'price' => 15.00,
                'cost' => 8.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'ID String Rope',
                'barcode' => 'IS-001',
                'description' => 'Durable ID string, assorted colors',
                'category_id' => 2,
                'unit' => 'piece',
                'price' => 8.00,
                'cost' => 4.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Fabrics (category_id: 3)
            [
                'product_name' => 'School Uniform Fabric White',
                'barcode' => 'SF-WHT-001',
                'description' => 'White cotton polyester blend for school uniforms',
                'category_id' => 3,
                'unit' => 'yard',
                'price' => 120.00,
                'cost' => 85.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'School Uniform Fabric Blue',
                'barcode' => 'SF-BLU-001',
                'description' => 'Navy blue fabric for school uniforms',
                'category_id' => 3,
                'unit' => 'yard',
                'price' => 125.00,
                'cost' => 90.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'PE Uniform Fabric',
                'barcode' => 'PE-FAB-001',
                'description' => 'Dri-fit fabric for PE uniform',
                'category_id' => 3,
                'unit' => 'yard',
                'price' => 150.00,
                'cost' => 110.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Plaid Fabric Red',
                'barcode' => 'PL-RED-001',
                'description' => 'Red plaid pattern for skirts',
                'category_id' => 3,
                'unit' => 'yard',
                'price' => 140.00,
                'cost' => 100.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Lamination Materials (category_id: 4)
            [
                'product_name' => 'Laminating Sheet A4',
                'barcode' => 'LS-A4-100',
                'description' => 'Clear laminating sheets, 100 pieces',
                'category_id' => 4,
                'unit' => 'pack',
                'price' => 280.00,
                'cost' => 200.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Laminating Sheet Legal',
                'barcode' => 'LS-LGL-100',
                'description' => 'Legal size laminating sheets, 100 pieces',
                'category_id' => 4,
                'unit' => 'pack',
                'price' => 320.00,
                'cost' => 230.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Laminating Pouch ID Size',
                'barcode' => 'LP-ID-100',
                'description' => 'ID card size laminating pouches, 100 pieces',
                'category_id' => 4,
                'unit' => 'pack',
                'price' => 150.00,
                'cost' => 100.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Laminating Film Roll',
                'barcode' => 'LF-ROLL-001',
                'description' => '100 meter laminating film roll',
                'category_id' => 4,
                'unit' => 'roll',
                'price' => 1200.00,
                'cost' => 900.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Binding Materials (category_id: 5)
            [
                'product_name' => 'Plastic Binding Cover Clear',
                'barcode' => 'BC-CLR-100',
                'description' => 'Transparent plastic covers, 100 pieces',
                'category_id' => 5,
                'unit' => 'pack',
                'price' => 220.00,
                'cost' => 160.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Plastic Binding Cover Colored',
                'barcode' => 'BC-COL-100',
                'description' => 'Colored plastic covers, assorted, 100 pieces',
                'category_id' => 5,
                'unit' => 'pack',
                'price' => 250.00,
                'cost' => 180.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Spiral Binding Wire',
                'barcode' => 'SW-001',
                'description' => 'Metal spiral binding wire, assorted sizes',
                'category_id' => 5,
                'unit' => 'piece',
                'price' => 8.00,
                'cost' => 4.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Plastic Binding Comb',
                'barcode' => 'PBC-001',
                'description' => 'Plastic binding combs, various sizes',
                'category_id' => 5,
                'unit' => 'piece',
                'price' => 12.00,
                'cost' => 6.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Uniform Accessories (category_id: 6)
            [
                'product_name' => 'School Button White',
                'barcode' => 'BTN-WHT-100',
                'description' => 'White buttons for school uniforms, 100 pieces',
                'category_id' => 6,
                'unit' => 'pack',
                'price' => 50.00,
                'cost' => 30.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'School Button Gold',
                'barcode' => 'BTN-GLD-100',
                'description' => 'Gold buttons for uniform blazers, 100 pieces',
                'category_id' => 6,
                'unit' => 'pack',
                'price' => 80.00,
                'cost' => 50.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Embroidered Patch',
                'barcode' => 'EP-001',
                'description' => 'Custom school logo embroidered patch',
                'category_id' => 6,
                'unit' => 'piece',
                'price' => 35.00,
                'cost' => 20.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Zipper Standard',
                'barcode' => 'ZIP-STD-001',
                'description' => 'Standard zipper, assorted colors and sizes',
                'category_id' => 6,
                'unit' => 'piece',
                'price' => 18.00,
                'cost' => 10.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'Velcro Strip',
                'barcode' => 'VLC-001',
                'description' => 'Hook and loop velcro strip, 1 meter',
                'category_id' => 6,
                'unit' => 'meter',
                'price' => 25.00,
                'cost' => 15.00,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
